on:
  workflow_call:
    inputs:
      release-type:
        required: true
        description: release type
        default: "node"

name: Release
jobs:
  release-please:
    runs-on: macos-14
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ${{ inputs.release-type }}
          package-name: release-please-action
